### ISSUE TITLE
Question about pgltools merge

### ISSUE THREAD

**Issue by QianzhaoJ** [billgreenwald/pgltools#9]
Hi :
    I'm going to try the methods of loop calling in your article [https://doi.org/10.1038/s41467-019-08940-5](url) , and this method for loop calling is very useful and accurate !
    First, I called loops for each resolution using juicer (5kb to 25kb, 1 kb bin-size interval) , then I combine loop calls from all resolutions using `cat  all_res_loop/*/merged_loops.bedpe | grep -v "#" > allres.loop` , and merge loops within 20kb using `pgltools formatbedpe allres.loop  > allres_loop.pgl`  and `pgltools merge -a all_loop.pgl -noH -d 20000 > merged_all_loop.pgl`.
We can see the lcoation of merged loop is accurate in the picture but the size of some loop anchors are so long. I downloaded the merged loop in your article, and found the max size of these loop anchors are 60 kb. So, counld you give me some suggestions?
![image](https://user-images.githubusercontent.com/42069662/92901574-2a751300-f453-11ea-82e9-87f0adcf0820.png)

   Thanks in advance !
Best wishes
Qianzhao

**Comment by billgreenwald** [comment]
Hey Qianzhao,

I'm super glad you tried out the methods we used to call loops in that paper; we found them to work really well, and they aren't the most straightforward/require running this multiple times, so I wasn't sure if others would try it.  I am happy to help how I can.

To give a little context on why we did what we did since I think it'll help follow the methods I am typing in a second: we saw that many papers used the highest resolution loop call they could possibly use with their data.  Additionally, within the hiccups methods, they actually bin the data into lower resolutions (ie 25kb), look for support of the loop in that higher resolution (ie 25kb), and then go back down to the higher resolution you originally passed as a parameter (ie 5kb) and label the loop as being at the high resolution location.  In other words, the low resolution/larger anchors are there to give support to the findings at the high resolution/smaller anchors.  But, the loop call is made/placed at the high reoslution/small anchor level.

Ok, so for the method.  We slightly tweaked what you did, and then wrote a small script after pgltools ran to get the final loop set.  

First, for each individual bedpe at one resolution, add a column with a unique index to it (this index should be unique across all your files).  For example, something like (and I'm typing this just in git so syntax editing may be slightly necessary)
```
for resolution in `seq 5 25`; do
    awk -V seq=$seq '{print $0\t$seq,kbNR}'
done
```
Lets assume for the rest of the code you had only 6 columns in that starting bedpe; your unique identifier is now in column 7.

Then run your command to cat all the files, and merge them down using the "-c 7 -o collapse -delim ;" options.  So
```
pgltools merge -a all_loop.pgl -noH -d 20000 -c 7 -o collapse -delim ";" > merged_all_loop.pgl
```

Now your merged_all_loop.pgl will have an extra column that contains a comma separated list of all loops that overlapped for each call.  Now we use a new script that, for each loop in the final loop set, either (a) keeps it because it was called in at least 3 resolutions (which you can figure out from your unique IDs), or (B) discards it because it was called in only 1 or 2 resolutions.  Finally, *instead of using the loop calls directly in merged_all_loop*, we go back to the original files and extract out the matching loop that had the smallest resolution (using the unique IDs). 

 For example, lets say one loops has the IDs 5kb,100;6kb,200,10kb,250.  

We would see that it was called in 3 resolutions, so we keep it, and then we would save the loop call as the loop that had the id 5kb,100 in the original 5kb loop call file.

Once again, we do this so that we get *support* for our calls from lower resolutions/larger anchors, but we *keep* the highest resolution/smallest anchors in the loop call set like hiccups does.  

Side note: the reason some of our anchors go up to 60kb is we used both hiccups and another method escaping me right now; the other method had lower resolutions used for calling, so that 60kb loop was actually called at 60kb as the highest resolution

**Comment by QianzhaoJ** [comment]
Hi :
Thanks for your quick reply, that's very helpful ! And it works ! 
But I have one other questions. 
I have multiple samples and I want to get an union loop set. I have merged all loop file in each samlpe, and next should I merge all sample like previous methods and retain the highest resolution loop again?
Thank you very much anyway!
Best wishes
Qianzhao

**Comment by billgreenwald** [comment]
Hi Qianzhao,

I would suggest keeping the highest resolution loop as before, but this time, keeping all loops even if they were only called in one, as you already have filtered by confidence using multiple resolutions in the last step.  If a loop call overlaps with two samples at the same resolution, I would keep the call from the dataset that had the deepest sequencing coverage. 

These are the methods I used in the islet HiC data from another one of my papers https://www.nature.com/articles/s41467-019-09975-4#Sec9

Best,
Bill

**Comment by QianzhaoJ** [comment]
Hi Bill,

Good strategy ! I really appreciate your help !

Best,
Qianzhao
